using FuturesSignalsBot.Models;

namespace FuturesSignalsBot.Storage;

public class CryptocurrenciesStorage
{
    public readonly List<Cryptocurrency> AllCryptocurrencies =
    [
        new("1000000BOBUSDT"), new("1000000MOGUSDT"), new("1000BONKUSDT"), new("1000CATUSDT"),
    new("1000CHEEMSUSDT"), new("1000FLOKIUSDT"), new("1000LUNCUSDT"), new("1000PEPEUSDT"),
    new("1000RATSUSDT"), new("1000SATSUSDT"), new("1000WHYUSDT"),
    new("1000XECUSDT"), new("1INCHUSDT"), new("1MBABYDOGEUSDT"), new("A2ZUSDT"),
    new("ACEUSDT"), new("ACHUSDT"), new("ACTUSDT"),
    new("ACXUSDT"), new("AERGOUSDT"), new("AEROUSDT"),
    new("AEVOUSDT"), new("AGLDUSDT"), new("AGTUSDT"), new("AINUSDT"),
    new("AIOTUSDT"), new("AIOUSDT"), new("AIUSDT"), new("AIXBTUSDT"),
    new("AKTUSDT"), new("ALCHUSDT"), new("ALGOUSDT"), new("ALICEUSDT"),
    new("ALLUSDT"), new("ALPINEUSDT"), new("ALTUSDT"), new("ANIMEUSDT"),
    new("ANKRUSDT"), new("APEUSDT"), new("API3USDT"), new("APTUSDT"),
    new("ARBUSDT"), new("ARCUSDT"), new("ARKMUSDT"), new("ARKUSDT"),
    new("ARPAUSDT"), new("ARUSDT"), new("ASRUSDT"), new("ASTRUSDT"),
    new("ATAUSDT"), new("ATHUSDT"), new("ATOMUSDT"), new("AUCTIONUSDT"),
    new("AUSDT"), new("AVAAIUSDT"), new("AVAUSDT"),
    new("AWEUSDT"), new("AXLUSDT"), new("AXSUSDT"), new("B2USDT"),
    new("B3USDT"), new("BABYUSDT"), new("BANANAS31USDT"), new("BANANAUSDT"),
    new("BANDUSDT"), new("BANKUSDT"), new("BANUSDT"), new("BATUSDT"),
    new("BBUSDT"), new("BDXNUSDT"), new("BEAMXUSDT"),
    new("BELUSDT"), new("BERAUSDT"), new("BICOUSDT"), new("BIDUSDT"),
    new("BIGTIMEUSDT"), new("BIOUSDT"), new("BLURUSDT"), new("BMTUSDT"),
    new("BNTUSDT"), new("BOMEUSDT"), new("BRETTUSDT"),
    new("BROCCOLI714USDT"), new("BROCCOLIF3BUSDT"), new("BRUSDT"), new("BSVUSDT"),
    new("BTCUSDT"), new("BULLAUSDT"), new("BUSDT"), new("C98USDT"),
    new("CAKEUSDT"), new("CARVUSDT"), new("CATIUSDT"), new("CELOUSDT"),
    new("CELRUSDT"), new("CETUSUSDT"), new("CFXUSDT"), new("CGPTUSDT"),
    new("CHESSUSDT"), new("CHILLGUYUSDT"), new("CHRUSDT"), new("CHZUSDT"),
    new("CKBUSDT"), new("COMPUSDT"), new("COOKIEUSDT"), new("COSUSDT"),
    new("COTIUSDT"), new("COWUSDT"), new("CROSSUSDT"), new("CRVUSDT"),
    new("CTKUSDT"), new("CTSIUSDT"), new("CUSDT"), new("CVCUSDT"),
    new("CVXUSDT"), new("CYBERUSDT"), new("DASHUSDT"), new("DEEPUSDT"),
    new("DEGENUSDT"), new("DEGOUSDT"), new("DENTUSDT"), new("DEXEUSDT"),
    new("DFUSDT"), new("DIAUSDT"), new("DMCUSDT"), new("DODOXUSDT"),
    new("DOGSUSDT"), new("DOLOUSDT"), new("DOODUSDT"),
    new("DRIFTUSDT"), new("DUSDT"), new("DUSKUSDT"),
    new("DYDXUSDT"), new("DYMUSDT"), new("EDUUSDT"), new("EGLDUSDT"),
    new("EIGENUSDT"), new("ENAUSDT"), new("ENJUSDT"), new("ENSUSDT"),
    new("EPICUSDT"), new("EPTUSDT"), new("ERAUSDT"), new("ESPORTSUSDT"),
    new("ETHFIUSDT"), new("ETHWUSDT"), new("ETHUSDT"),
    new("FARTCOINUSDT"), new("FETUSDT"), new("FHEUSDT"), new("FIDAUSDT"),
    new("FIOUSDT"),
    new("FLOWUSDT"), new("FLUXUSDT"), new("FORMUSDT"), new("FORTHUSDT"),
    new("FUNUSDT"), new("FUSDT"), new("FXSUSDT"), new("GALAUSDT"),
    new("GASUSDT"), new("GHSTUSDT"), new("GLMUSDT"), new("GMTUSDT"),
    new("GMXUSDT"), new("GOATUSDT"), new("GPSUSDT"), new("GRASSUSDT"),
    new("GRIFFAINUSDT"), new("GRTUSDT"), new("GTCUSDT"), new("GUNUSDT"),
    new("GUSDT"), new("HAEDALUSDT"), new("HEIUSDT"),
    new("HFTUSDT"), new("HIGHUSDT"), new("HIPPOUSDT"), new("HIVEUSDT"),
    new("HMSTRUSDT"), new("HOMEUSDT"), new("HOOKUSDT"), new("HOTUSDT"),
    new("HUMAUSDT"), new("HUSDT"), new("HYPERUSDT"), new("HYPEUSDT"),
    new("ICNTUSDT"), new("ICXUSDT"), new("IDOLUSDT"),
    new("IDUSDT"), new("ILVUSDT"), new("IMXUSDT"), new("INITUSDT"),
    new("INJUSDT"), new("INUSDT"), new("IOSTUSDT"), new("IOTAUSDT"),
    new("IOTXUSDT"), new("IOUSDT"), new("IPUSDT"), new("JASMYUSDT"),
    new("JELLYJELLYUSDT"), new("JOEUSDT"), new("JSTUSDT"), new("JTOUSDT"),
    new("JUPUSDT"), new("KAIAUSDT"), new("KAITOUSDT"), new("KASUSDT"),
    new("KAVAUSDT"), new("KERNELUSDT"), new("KMNOUSDT"), new("KNCUSDT"),
    new("KOMAUSDT"), new("KSMUSDT"), new("LAUSDT"), new("LAYERUSDT"),
    new("LDOUSDT"), new("LISTAUSDT"), new("LPTUSDT"),
    new("LQTYUSDT"), new("LRCUSDT"), new("LSKUSDT"),
    new("LUMIAUSDT"), new("LUNA2USDT"), new("MAGICUSDT"), new("MANAUSDT"),
    new("MANTAUSDT"), new("MASKUSDT"), new("MAVIAUSDT"), new("MAVUSDT"),
    new("MBOXUSDT"), new("MELANIAUSDT"), new("MEMEUSDT"), new("MERLUSDT"),
    new("METISUSDT"), new("MEUSDT"), new("MEWUSDT"),
    new("MINAUSDT"), new("MLNUSDT"), new("MOCAUSDT"), new("MOODENGUSDT"),
    new("MORPHOUSDT"), new("MOVEUSDT"), new("MOVRUSDT"), new("MTLUSDT"),
    new("MUBARAKUSDT"), new("MUSDT"), new("MYXUSDT"), new("NAORISUSDT"),
    new("NEIROUSDT"), new("NEOUSDT"), new("NEWTUSDT"),
    new("NFPUSDT"), new("NILUSDT"), new("NKNUSDT"), new("NMRUSDT"),
    new("NOTUSDT"), new("NTRNUSDT"), new("NXPCUSDT"),
    new("OGNUSDT"), new("OGUSDT"), new("OLUSDT"), new("OMUSDT"),
    new("ONDOUSDT"), new("ONEUSDT"), new("ONGUSDT"), new("ONTUSDT"),
    new("OPUSDT"), new("ORCAUSDT"), new("ORDIUSDT"), new("OXTUSDT"),
    new("PARTIUSDT"), new("PAXGUSDT"), new("PENDLEUSDT"), new("PENGUUSDT"),
    new("PEOPLEUSDT"), new("PHAUSDT"), new("PHBUSDT"),
    new("PIPPINUSDT"), new("PIXELUSDT"), new("PLAYUSDT"), new("PLUMEUSDT"),
    new("PNUTUSDT"), new("POLUSDT"), new("POLYXUSDT"),
    new("POPCATUSDT"), new("PORTALUSDT"), new("POWRUSDT"),
    new("PROMPTUSDT"), new("PROMUSDT"), new("PROVEUSDT"), new("PUFFERUSDT"),
    new("PUMPBTCUSDT"), new("PUMPUSDT"), new("PUNDIXUSDT"), new("PYTHUSDT"),
    new("QNTUSDT"), new("QTUMUSDT"), new("RAREUSDT"),
    new("RAYSOLUSDT"), new("RDNTUSDT"), new("REDUSDT"),
    new("RENDERUSDT"), new("RESOLVUSDT"), new("REZUSDT"), new("RIFUSDT"),
    new("RLCUSDT"), new("RONINUSDT"), new("ROSEUSDT"), new("RPLUSDT"),
    new("RSRUSDT"), new("RUNEUSDT"), new("RVNUSDT"), new("SAFEUSDT"),
    new("SAGAUSDT"), new("SAHARAUSDT"), new("SANDUSDT"), new("SANTOSUSDT"),
    new("SCRTUSDT"), new("SCRUSDT"), new("SEIUSDT"), new("SFPUSDT"),
    new("SHELLUSDT"), new("SIGNUSDT"), new("SIRENUSDT"),
    new("SKLUSDT"), new("SKYAIUSDT"), new("SLPUSDT"), new("SNXUSDT"),
    new("SOLVUSDT"), new("SONICUSDT"), new("SOONUSDT"),
    new("SOPHUSDT"), new("SPELLUSDT"), new("SPKUSDT"), new("SPXUSDT"),
    new("SQDUSDT"), new("SSVUSDT"), new("STEEMUSDT"), new("STGUSDT"),
    new("STORJUSDT"), new("STOUSDT"), new("STRKUSDT"), new("STXUSDT"),
    new("SUNUSDT"), new("SUPERUSDT"), new("SUSDT"),
    new("SUSHIUSDT"), new("SWARMSUSDT"),
    new("SXTUSDT"), new("SYNUSDT"), new("SYRUPUSDT"), new("SYSUSDT"),
    new("TACUSDT"), new("TAGUSDT"), new("TAIKOUSDT"), new("TANSSIUSDT"),
    new("TAUSDT"), new("THETAUSDT"), new("THEUSDT"),
    new("TIAUSDT"), new("TLMUSDT"), new("TNSRUSDT"),
    new("TOWNSUSDT"), new("TRBUSDT"), new("TREEUSDT"),
    new("TRUMPUSDT"), new("TRUUSDT"), new("TSTUSDT"),
    new("TURBOUSDT"), new("TUSDT"), new("TUTUSDT"), new("TWTUSDT"),
    new("UMAUSDT"), new("USDCUSDT"), new("USELESSUSDT"),
    new("USUALUSDT"), new("VANAUSDT"), new("VANRYUSDT"), new("VELODROMEUSDT"),
    new("VELVETUSDT"), new("VETUSDT"), new("VICUSDT"), new("VINEUSDT"),
    new("VIRTUALUSDT"), new("VTHOUSDT"), new("VVVUSDT"),
    new("WALUSDT"), new("WAXPUSDT"), new("WCTUSDT"), new("WIFUSDT"),
    new("WLDUSDT"), new("WOOUSDT"), new("WUSDT"), new("XAIUSDT"),
    new("XMRUSDT"), new("XNYUSDT"),
    new("XTZUSDT"), new("XVGUSDT"), new("XVSUSDT"),
    new("YALAUSDT"), new("YFIUSDT"), new("YGGUSDT"), new("ZECUSDT"),
    new("ZENUSDT"), new("ZEREBROUSDT"), new("ZETAUSDT"), new("ZILUSDT"),
    new("ZKJUSDT"), new("ZKUSDT"), new("ZORAUSDT"), new("ZRCUSDT"),
    new("ZROUSDT"), new("ZRXUSDT")
    ];

    public Cryptocurrency? GetByName(string name)
           => AllCryptocurrencies.FirstOrDefault(c => c.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
    
}